### PR TITLE
Upgrade wyrihaximus/html-compress to new version

### PR DESCRIPTION
**Pull request by paavo**
As discussed here: https://github.com/flownative/neos-compressor/issues/8

### CODE REVIEW

**Comment by paavo** [comment]
does anyone have time to review my PR in the next weeks?
@kitsunet @kdambekalns

**Review by kdambekalns — CHANGES_REQUESTED** [review]
This could probably be updated to `"wyrihaximus/html-compress": "^3.0"` by now, but…

The update breaks rendering. I applied this to our website (where we use the package anyway), and it then looks like this:

Screenshot 2020-02-20 at 12 09 38

Seeing this I remembered that I had tried an update once, but gave up back then.

The effect looks like cache markers being broken and this leading to their detection and replacement no longer working.

**Comment by paavo** [comment]
@kitsunet if you find time i'll be very thankful if you could review the pull request @kdambekalns changed 🙏

**Review by kdambekalns — CHANGES_REQUESTED** [review]
Revisited this, but the situation is still as in https://github.com/flownative/neos-compressor/pull/9#pullrequestreview-361818249

It would be interesting to see if it works with the middleware approach (via https://github.com/middlewares/minifier)…

**Pull request closed without merging**
